
const DELETED_ITEMS = [
    'croptosis:fertilized_sand',
    'croptosis:fertilized_farmland',
    'croptosis:fertilized_dirt',
    'croptosis:potash_ore',
    'croptosis:apatite_ore',
    'croptosis:deepslate_apatite_ore',
    'croptosis:potash_block',
    'croptosis:apatite_block',
    'croptosis:feather_meal',
    'croptosis:rotten_pile',
    'croptosis:apatite',
    'croptosis:potash',
    'croptosis:potash_pieces',
    'nethersdelight:iron_machete',
    'nethersdelight:diamond_machete',
    'nethersdelight:netherite_machete',
    'nethersdelight:golden_machete',
    'farmersdelight:rope',
    'farmingforblockheads:feeding_trough',
    'supplementaries:quiver',
    'geodes:calcite_slab',
    'geodes:calcite_stairs',
    'farmersdelight:carrot_crate',
    'farmersdelight:potato_crate',
    'farmersdelight:beetroot_crate',
    'vinery:apple_crate',
    'croptopia:grape_seed',
    'blockus:paper_lamp',
    'croptopia:garlic_seed',
    'croptopia:onion_seed',
    'croptopia:rice_seed',
    'supplementaries:sugar_cube',
    'croptopia:coffee_beans',
    'croptopia:tea_leaves',
    'croptopia:grape',
    'croptopia:cherry'
];
REIEvents.hide('item', (event) => {
    DELETED_ITEMS.forEach(id => event.hide(id));
});
